import { LangPack } from "../types";

const en: LangPack = {
	"got-question-wrong-in-the-past": "You got this question wrong in the past",
	"submit-answer": "Submit answers",
	"accuracy-rate": "Accuracy",
	"per-question-spent": "Per question spent",
	"question-unit": "questions",
	"start-quiz": "Start",
	"exit-quiz": "Quit",
	minutes: "minute(s)",
	seconds: "second(s)",
	spent: "Spent",
	"got-x-out-of-y-questions-right":
		"You got ${totalCorrect} / ${totalSize} questions correct !",
	"quiz-summary": "Summary",
	"quiz-history": "History",
	"grade-one": "Grade 1",
	"grade-two": "Grade 2",
	"grade-three": "Grade 3",
	"within-100": "Within 100",
	"within-10": "Within 10",
	"within-20": "Within 20",
	"within-1k": "Within 1k",
	"within-10k": "Within 10k",
	addition: "Addition",
	subtraction: "Subtraction",
	"addition-and-subtraction": "Addition and subtraction",
	multiplication: "Multiplication",
	division: "Division",
	"fraction-addition": "Fraction addition",
	"fraction-subtraction": "Fraction subtraction",
	"fraction-addition-and-subtraction": "Fraction addition and subtraction",
	"division-rem": "Division with remainder",
	"one-number": "One number",
	"two-numbers": "Two numbers",
	"three-numbers": "Three numbers",
	"four-numbers": "Four numbers",
	"three-numbers-with-one-number": "Three numbers with one number",
	"math-quiz": "Math quiz",
	"short-months": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Oct",
		"Nov",
		"Dec"
	],
	"quiz-time": "${month} ${day} ${year} ${hour}:${minute}:${seconds}",
	"quiz-time-nosec": "${month} ${day} ${year} ${hour}:${minute}",
	yes: "Yes",
	no: "No",
	"confirm-submit-answers": "Are you sure you want to submit the answers?",
	"make-sure-check-answers":
		"Please double check your answers before submission.",
	"confirm-exit-quiz": "Are you sure you want to quit?"
};

export default en;
